### ISSUE TITLE
 Run 'python utils/visualize_env.py --env_name hammer-v0'  Cause - File "cymj.pyx", line 175, in mujoco_py.cymj.load_model_from_path

### ISSUE THREAD

**Issue by OOXXXXOO** [vikashplus/mj_envs#65]
LOGS:
Exception: Failed to load XML file: /home/pi/workspace/tanwenxuan/Project/mj_envs/mj_envs/envs/hand_manipulation_suite/assets/DAPG_hammer.xml. mj_loadXML error: b

"Error: could not open STL file '/home/pi/workspace/tanwenxuan/Project/mj_envs/mj_envs/envs/hand_manipulation_suite/assets/../../../sims/Adroit/resources/meshes/../../../robohive.stl'\nObject name = robohive, id = 11, line = 69, column = 9"

**Comment by vikashplus** [comment]
@OOXXXXOO 
1. Can you confirm which branch you are using?
2. Can you also confirm that you have followed the installation instructions. This seems like an error one would get if they skipped the submodule instantiations. Please follow the installation instructions closely if you haven't.
