### ISSUE TITLE
Visual interface black

### ISSUE THREAD

**Issue by SHYang1210** [vikashplus/mj_envs#7]
When I run python utils/visualize_env.py --env_name hammer-v0, I can run it. There is nothing in the loaded graphical interface. The interface is all black, I don't know how.

**Comment by aravindr93** [comment]
Hi @SHYang1210 I think this is due to the submodules not loading properly. Please follow the instructions exactly (it's quite sensitive). In particular, you should clone the repo not in the conventional way, but with the recursive flag.

```
$ git clone --recursive https://github.com/vikashplus/mj_envs.git
```
Then update the submodules using
```
$ cd mj_envs  
$ git submodule update --remote
```

**Comment by anilsh** [comment]
Is it resolved? I am able to run everything properly but getting no visualization. Any suggestions?

It runs only when I use `xvfb-run bash`. But no visualization.
